### ISSUE TITLE
Auto Installing Repo in HACS with each reboot

### ISSUE THREAD

**Issue by mrpool217** [hasl-sensor/lovelace-hasl-departure-card#10]
The sensor plugins and departure card repositories being are automatically installed on their system via HACS?  I am in the USA so there is no need for the Swedish bus system plugin to be installed.  I did not install that repo but it is there.  I deleted the card and the sensor repositories, rebooted HA and it returned as a New Repository.  Happens every time I reboot and has been doing this for the past few days.  To me, this seems like a potential security issue!!

**Comment by dimmanramone** [comment]
@mrpool217 I don't really undestand, if you don't activelly install the cards, they don't get installed automatically. This seems more than a HACS issue.

**Comment by mrpool217** [comment]
It has been found and they said it was a HACS issue.  I am sorry for
placing the issue on your git but I was not sure what the source was so I
posted in both locations.  The actual issue wasn't that the cards were
being installed but rather the Custom Repositories for your card and sensor
were being installed automatically into HACS on my instance of Home
Assistant.  If I removed them and rebooted, they would come back after I
rebooted.  I posted in DrZZs discord to see if it was something I did wrong
and several people found the same thing happening for them.  I then posted
the issue to make sure we could find the cause and fix it as soon as
possible.

*Although I have no use for the HASL card and sensor, I appreciate your
hard work on those.  Please keep up the good work and effort!*

Also, thank you for responding to my posting.  I have been busy with work
and only just now have been able to return home and reply.  I work in the
medical field and this COVID thing has been keeping me really busy.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
