### ISSUE TITLE
Wider time frame for departures

### ISSUE THREAD

**Issue by rasssta** [hasl-sensor/lovelace-hasl-departure-card#11]
Not sure what the default "time frame" is for departures, but for bus stops with only one or two bus lines passing by it can be 1-2h between each departure so it would be nice to see departures for the next 6-8 hours, or preferably even 24 hours and then limit it by max_departures 5 or similar.

**Comment by dimmanramone** [comment]
@rasssta This is something that should be changed in the component and not the lovelace card, though the version 2 of the component is not under development anymore. A [new version (3)](https://github.com/hasl-sensor/integration) is under development and you can post a feature request there.




> Seems like CONF_TIMEWINDOW is set to 30 as default but only 60 as possible max limit. Will it cause any problems to increase the following config to max 1440?
> 
> ```
>             vol.All(vol.Coerce(int), vol.Range(min=0, max=60)),
> ```

I don't think that it will cause any problem, but I'm not sure if the API is supporting a time frame of 24 hours.
