### ISSUE TITLE
line issue.

### ISSUE THREAD

**Issue by fredrikbuchanan** [hasl-sensor/lovelace-hasl-departure-card#17]
Hi. I have a weird issue.
if i specifies the lines as 181, 184 it will also add 18 to the sensor. despite me not refering to it in the config.
it is the departure sensor

**Comment by DSorlov** [comment]
Try with no space so "181, 184" becomes "181,184".

**Comment by fredrikbuchanan** [comment]
have now tried it but it did not  make any difference
