### ISSUE TITLE
Error message when "Update: true"

### ISSUE THREAD

**Issue by kattelk** [hasl-sensor/lovelace-hasl-departure-card#19]
I am using HASL to get the departure times for a bus stop using the SL Realtidsinformation 4 API.

In the HASL depature card, I would like to set the option "Update: true", so that I know when the data on the card is out of date.  However, when I do this, I get the error ! "this is undefined".  (Before some recent update this error used to say "Cannot read properties of undefined (reading 'config')".  I get the same error independent of the bus stop used.

Is there anything I can do to work around this issue (apart from setting "Update: false")?

**Comment by mountaindude** [comment]
I am also seeing this.
Looked into it real quick and it seems there's a scoping problem in the code. 

![image](https://user-images.githubusercontent.com/1029262/203840650-5e89da7f-1cab-453b-af13-80d6653f689b.png)

**Comment by DSorlov** [comment]
Fixed in #22
