### ISSUE TITLE
Standard setup throwing "this is undefined"

### ISSUE THREAD

**Issue by Rydberg95** [hasl-sensor/lovelace-hasl-departure-card#29]
Adding the card as instructed renders "this is undefined" in the card header. It seems to be picking up the JS file, but that the JS during runtime is throwing the error.

 I tried both adding it via HACS and manually. HASL as data feed seems to getting the data correctly, since I can see departure times when viewing the entity in HA.

File location for the JS script (when adding via HACS) is _.../www/community/lovelace-hasl-departure-card/hasl-departure-card.js_

HA-version: 2023.2.2
HACS-version: 1.30.1 (20220906112053)

Browser used: Firefox v108.

When running in Chromium, the error displayed is instead "Cannot read properties of undefined (reading 'config')", but my guess is that the origin is the same..?

Card config us **exactly** as mentioned in docs, which the only change being the entity line:
`sensor.sl_departure_sensor_2193_hasl_sl_departures`

**Comment by morlic** [comment]
could it be related to #19 and #24?

**Comment by matfouc** [comment]
I ran personally into this issue his week-end and i figured out that i need to specifically  choose "master" branch when installing this custom card.
By default HACS suggests automatically to install version 2.6.0 which doesn't include latest fixes like in #19  or #24 .

@DSorlov, perhaps you could release a new version when you have time

**Comment by Rydberg95** [comment]
> could it be related to #19 and #24?

Looks like it is. However, shouldn't the issue appear for everyone since I haven't changed anything? I'm not sure what parts I should change to make it work.

**Comment by Rydberg95** [comment]
> By default H

That worked fine. Thanks!
