### ISSUE TITLE
updated: true show "Last updated Invalid Date"

### ISSUE THREAD

**Issue by PerJarlemark** [hasl-sensor/lovelace-hasl-departure-card#30]
When "updated: true" I get an error showing "Last updated Invalid Date"

Version 2..6.1
Using SL Departure Sensor 
API: SL Realtidsinformation 4

**Comment by Hellboj1** [comment]
Same

**Comment by PerJarlemark** [comment]
Tack Daniel, uppdateringen funkar kanon :-)
