### ISSUE TITLE
Increase text size?

### ISSUE THREAD

**Issue by TrespassingTortoise** [hasl-sensor/lovelace-hasl-departure-card#33]
Is there a way to increase the size of the departure time? I have a dashboard on the wall at home and would like to see the time from further away.

<img width="594" alt="image" src="https://github.com/hasl-sensor/lovelace-hasl-departure-card/assets/143438157/57144a70-e5db-48bb-8125-ad58eeee6b9b">

**Comment by DSorlov** [comment]
Hi. It is not currently supported.
